---
title: "Fleet, reference table, documentation"
author: "Kirsten Birch Håkansson, DTU Aqua"
date: "\today"
output:
  pdf_document: default
---



```{r setup, include = F}
knitr::opts_chunk$set(echo = TRUE, message = F, warnings = F)

library(dplyr)
library(lubridate)

options(scipen = 999)

path_out <- "Q:/mynd/SAS Library/fleet/" 
filename_out <- "fleet_old_metiers"

library(dplyr)
library(lubridate)

years <- c(1987:2024)

```

# Data 

Input a list of all metiers used 1987-2018

```{r data, eval = T}


# rdb <- read.csv("Q:/mynd/SAS Library/FiskeriAktiviteter/references/RDB/AreaCodeFACCodeRegion.csv")
# 
# #A bit of renaming and deletion of id's not needed presently
# 
# rdb <- select(rename(rdb, area = AreaCode, metier_lvl6 = FishingActivityCategoryEuropeanLvl6Code), area, metier_lvl6)

dfad <- readRDS("Q:/mynd/SAS Library/fleet/data/metiers_exist.rds")

dfad_sum <- summarise(group_by(dfad, fao_area, merged_metier_level6, fdfmark, metier_level6_ret), 
                      kg = sum(kg), trips = sum(trips))

fleet <- dfad_sum

```


# mixfish_fleet

Also need a mixfish_fleet for saithe, haddock and cod

The fleet are in principal coded from Q:/mynd/SAS Library/fleet/references/Fisheries_Data_call 2023_CoverLetter&Text_v2.pdf, if not this is msntioned below.

```{r}

mix <-
  mutate(
    fleet,
    metier_in = ifelse(
      is.na(merged_metier_level6) | merged_metier_level6 == "",
      metier_level6_ret ,
      merged_metier_level6
    )
  )

mix$mixfish_fleet <- NA

mix_1 <- c()

for (i in (1:nrow(mix))) {
  mixi <- mix[i, ]
  
  # 27.7.d ----
  # See stuff at Q:/mynd/SAS Library/fleet/analyses/area_7d
  if (mixi$fao_area %in% c("27.7.d")) {
    # TBB
    mixi$mixfish_fleet[mixi$metier_in == "TBB_CRU_16-31_0_0"] <- "TBB_CRU_16-31_0_0_all"
    mixi$mixfish_fleet[mixi$metier_in == "TBB_CRU_70-99_0_0"] <- "TBB_CRU_70-99_0_0_all"
    mixi$mixfish_fleet[mixi$metier_in == "TBB_DEF_>=120_0_0"] <- "TBB_DEF_>=120_0_0_all"
    
    # OTB
    mixi$mixfish_fleet[mixi$metier_in == "OTB_CRU_16-31_0_0"] <- "OTB_CRU_16-31_0_0_all"
    mixi$mixfish_fleet[mixi$metier_in == "OTB_CRU_32-69_0_0"] <- "OTB_CRU_32-69_0_0_all"
    mixi$mixfish_fleet[mixi$metier_in == "OTB_DEF_32-69_0_0"] <- "OTB_DEF_32-69_0_0_all" 
    #Above, Data from 1987-2024. This is a Norway Pout fishery. So we catch NOP in area 27.7.d?
    mixi$mixfish_fleet[mixi$metier_in == "OTB_MCD_70-99_0_0"] <- "OTB_CRU_70-99_0_0_all"
    mixi$mixfish_fleet[mixi$metier_in == "OTB_MCD_100-119_0_0"] <- "OTB_DEF_100-119_0_0_all" 
    #Above, check - this is not according to the annex, since I have stolen the fleet from another area. 
    #Maybe this could be split into CRU / DEF instead of hardcoding.
    mixi$mixfish_fleet[mixi$metier_in == "OTB_MCD_>=120_0_0"] <- "OTB_DEF_>=120_0_0_all"
    
    # IBC
    mixi$mixfish_fleet[mixi$metier_in %in% c("OTM_SPF_16-31_0_0",
                                             "OTB_SPF_>=120_0_0",
                                             "OTB_DEF_16-31_0_0")] <- "MIS_MIS_0_0_0_IBC" 
    #Above, Data from 1987-2024. OTB_SPF_>=120_0_0 is trips with 999 in mesh and catching PIL and BRS
    
    # SPF_32-69
    mixi$mixfish_fleet[mixi$metier_in == "OTM_SPF_32-69_0_0"] <- "OTM_SPF_32-69_0_0_all" 
    #Above, This is not according to the annex, since I have stolen the fleet from another area
    
    # LLS
    mixi$mixfish_fleet[substr(mixi$metier_in, 1, 3) == "LLS"] <- "LLS_FIF_0_0_0_all"
    
    # GNS
    mixi$mixfish_fleet[mixi$metier_in == "GNS_DEF_100-119_0_0"] <- "GNS_DEF_100-119_0_0_all"
    mixi$mixfish_fleet[mixi$metier_in == "GNS_DEF_120-219_0_0"] <- "GNS_DEF_120-219_0_0_all"
    mixi$mixfish_fleet[mixi$metier_in == "GNS_DEF_>=220_0_0"] <- "GNS_DEF_>=220_0_0_all"
    
    # All other
    mixi$mixfish_fleet[mixi$metier_in == "No_Matrix6"] <- "MIS_MIS_0_0_0_HC" 
    #Above, data from 1987-2024. This is a bit rough, but for most of the data it is True. There are two BRS / PIL trips that get this one
    
  }
  else if (mixi$fao_area %in% c("27.4.a", "27.4.b", "27.4.c")) {
    
    # TBB
    mixi$mixfish_fleet[mixi$metier_in == "TBB_CRU_16-31_0_0"] <- "TBB_CRU_16-31_0_0_all"
    mixi$mixfish_fleet[mixi$metier_in == "TBB_CRU_70-99_0_0"] <- "TBB_CRU_70-99_0_0_all"
    mixi$mixfish_fleet[mixi$metier_in == "TBB_DEF_>=120_0_0"] <- "TBB_DEF_>=120_0_0_all"
    
    # OTB
    mixi$mixfish_fleet[mixi$metier_in == "OTB_CRU_16-31_0_0"] <- "OTB_CRU_16-31_0_0_all"
    mixi$mixfish_fleet[mixi$metier_in == "OTB_CRU_32-69_0_0"] <- "OTB_CRU_32-69_0_0_all"
    mixi$mixfish_fleet[mixi$metier_in == "OTB_DEF_32-69_0_0"] <- "OTB_DEF_32-69_0_0_all" 
    mixi$mixfish_fleet[mixi$metier_in == "OTB_MCD_70-99_0_0"] <- "OTB_CRU_70-99_0_0_all"
    mixi$mixfish_fleet[mixi$metier_in == "OTB_MCD_100-119_0_0"] <- "OTB_DEF_100-119_0_0_all" 
    mixi$mixfish_fleet[mixi$metier_in == "OTB_MCD_>=120_0_0"] <- "OTB_DEF_>=120_0_0_all"
    
    # SDN
    mixi$mixfish_fleet[mixi$metier_in %in% c("SDN_DEF_>=120_0_0")] <- "SDN_DEF_>=120_0_0_all"
    mixi$mixfish_fleet[mixi$metier_in %in% c("SDN_DEF_100-119_0_0")] <- "SDN_DEF_100-119_0_0_all"
    #Above, not sure SDN_DEF_100-119_0_0 is a mixfish fleet in the North se, but the code is in the vocab
    #Before these two metiers werre joined in >=120
    
    # SSC
    mixi$mixfish_fleet[mixi$metier_in %in% c("SSC_DEF_>=120_0_0")] <- "SSC_DEF_>=120_0_0_all"
    mixi$mixfish_fleet[mixi$metier_in %in% c("SSC_DEF_100-119_0_0")] <- "SSC_DEF_100-119_0_0_all"
    #Above, not sure SDN_DEF_100-119_0_0 is a mixfish fleet in the North sea, but the code is in the vocab
    
    # GNS
    mixi$mixfish_fleet[mixi$metier_in == "GNS_DEF_90-99_0_0"] <- "GNS_DEF_90-99_0_0_all"
    mixi$mixfish_fleet[mixi$metier_in == "GNS_DEF_100-119_0_0"] <- "GNS_DEF_100-119_0_0_all"
    mixi$mixfish_fleet[mixi$metier_in == "GNS_DEF_120-219_0_0"] <- "GNS_DEF_120-219_0_0_all"
    mixi$mixfish_fleet[mixi$metier_in == "GNS_DEF_>=220_0_0"] <- "GNS_DEF_>=220_0_0_all"
    
    # LLS
    mixi$mixfish_fleet[substr(mixi$metier_in, 1, 3) == "LLS"] <- "LLS_FIF_0_0_0_all"
    
    # FPO
    mixi$mixfish_fleet[mixi$metier_in == "FPO_CRU_>0_0_0"] <- "FPO_CRU_>0_0_0_all"
    
    # SPF_32-69
    mixi$mixfish_fleet[mixi$metier_in == "OTM_SPF_32-69_0_0"] <- "OTM_SPF_32-69_0_0_all" 
    #Above, This is not according to the annex, since I have stolen the fleet from another area
    #In the past we would probably not have submitted this fleet, since it normally don't catch 
    #stocks under WGNSSK & MIXFISH. It has been included, since we now include all effort.
    
    # IBC
    mixi$mixfish_fleet[mixi$metier_in %in% c("OTM_SPF_16-31_0_0",
                                             "OTB_DEF_<16_0_0",
                                             "OTB_DEF_16-31_0_0",
                                             "OTB_SPF_>=120_0_0",
                                             "OTM_SPF_>=120_0_0")] <- "MIS_MIS_0_0_0_IBC" 
    #Above, data from 1987-2024. SPF_>=120_0_0 is trips mainly with 999 in mesh and catching SPF
    #OTB_SPF_>=120_0_0 & OTM_SPF_>=120_0_0 are mainly from unsorted fisheries
    
    # DRB_MOL
    mixi$mixfish_fleet[mixi$metier_in == "DRB_MOL_>=0_0_0"] <- "DRB_MOL_>=0_0_0_all"
    #Above, This is not according to the annex, since I have stolen the fleet from another area
    #In the past we would probably not have submitted this fleet, since it normally don't catch 
    #stocks under WGNSSK & MIXFISH. It has been included, since we now include all effort.
    
    
    # PS
    mixi$mixfish_fleet[substr(mixi$metier_in, 1, 2) == "PS"] <- "PS"
    #Above, This is not according to the annex, since I have stolen the fleet from another AWG.
    #The fleet is not in the MIXFISH list
    #In the past we would probably not have submitted this fleet, since it normally don't catch 
    #stocks under WGNSSK & MIXFISH. It has been included, since we now include all effort.
    
    # All other
    mixi$mixfish_fleet[substr(mixi$metier_in, 1, 3) == "No_"] <- "MIS_MIS_0_0_0_HC" 
    mixi$mixfish_fleet[is.na(mixi$mixfish_fleet)] <- "MIS_MIS_0_0_0_HC" 
    
  }
  mix_1 <- rbind(mix_1, mixi)
}


area_7d <-
  summarise(group_by(filter(mix_1, fao_area %in% c("27.7.d")),
           metier_level6_ret,
           mixfish_fleet),
           kg = sum(kg),
           trips = sum(trips)
  )

area_4 <-
  arrange(summarise(group_by(filter(mix_1, fao_area %in% c("27.4.a", "27.4.b", "27.4.c")),
           metier_level6_ret,
           mixfish_fleet),
           kg = sum(kg),
           trips = sum(trips)
  ), -kg)

area_4$pct_cum <- cumsum(area_4$kg)*100/sum(area_4$kg)

fleet <- mix_1

# rm(mix, mix_1)
```


```{r output, include = T}

matrix_out <-
  distinct(
    ungroup(fleet),
    fao_area,
    metier_level6_ret,
    # obs_at_sea_fleets_no_gns,
    # obs_at_sea_fleets_gns,
    # merged_metier_level6,
    mixfish_fleet
  )

matrix_out

# matrix_out <- rename(matrix_out, metier_level6 = metier_level6_ret)

saveRDS(matrix_out, paste0(path_out, filename_out, ".rds"))
write.csv(matrix_out, paste0(path_out, filename_out, ".csv"), row.names = F)

```


