---
title: "Fleet, reference table, documentation"
author: "Kirsten Birch Håkansson, DTU Aqua"
date: "\today"
output:
  html_document:
    toc: true
---

```{r setup, include = F}

knitr::opts_chunk$set(echo = TRUE, message = F, warnings = F)

options(scipen = 999)

path_in <- "../fleet/data/"
path_out <- "../analyses/area_3a_mix/" 
filename_out <- "area_3a_mix"

options(scipen = 999)

library(haven)
library(dplyr)
library(lubridate)
library(beepr)

years <- c(2015:2024)

art <- c("TOR", "RSP", "DVH", "DVR")
```

# Data
Pick all trips with some landings from area 27.7.d

```{r data}

dat <- readRDS(paste0(path_in, "metiers_exist_", min(years), "_", max(years),".rds"))

```


# Test metier relation

```{r}

fleet_old <- readRDS("../fleet/fleet_old_metiers.rds")

dat_3a <- subset(dat, fao_area %in% c("27.3.a.20", "27.3.a.20"))

dat_1 <- left_join(dat_3a, fleet_old, by = c("fao_area" = "fao_area", "metier_level6_ret" = "metier_level6_ret"))

```

```{r}

```

# What is OTB_DEF_32-69_0_0

```{r}

met <- subset(dat, metier_level6_ret =="OTB_DEF_32-69_0_0")

met_1 <- subset(dat, match_alle %in% met$match_alle)

met_sum <-
  summarise(
    group_by(
      met,
      art,
      target_spp_haul,
      fao_area
    ),
    kg = sum(kg),
    trips = sum(trips)
  )

unique(met_1$metier_level6_ret)

```


